export { App, type AppProps, type Capabilities } from './App.tsx'
export { PairScreen, codeFromInput } from './PairScreen.tsx'
export type { PushCapability } from './touch/SettingsScreen.tsx'
export type { AppCapability } from './appUpdate.ts'
export { t } from './i18n.ts'
export { DesktopShell, type BackendEntry } from './DesktopShell.tsx'
