import { z } from 'zod'
import { itemSchema, permissionModeSchema, projectConfigSchema, sessionInfoSchema } from './model.ts'

// Commands a client can send (`{t:'cmd', id, name, args}`), with the schema of their args and result.
// Phase 1 set; later phases add blob.get, files.upload, devices.*, …

const tabId = z.string().min(1)
const empty = z.object({})

export const modelInfoSchema = z.looseObject({ value: z.string(), displayName: z.string(), description: z.string() })
export const slashCommandSchema = z.looseObject({ name: z.string(), description: z.string(), argumentHint: z.string() })

export const COMMANDS = {
  'tab.create': {
    // tabId is generated by the client; a duplicate returns the existing tab, and so does a session another tab owns.
    args: z.object({
      tabId,
      cwd: z.string().min(1),
      resume: z.string().optional(),
      title: z.string().optional(),
      model: z.string().optional(),
      mode: permissionModeSchema.optional()
    }),
    result: z.object({ tabId: z.string() })
  },
  'tab.close': { args: z.object({ tabId }), result: empty },
  // Renames the tab and, when it has one, its stored session.
  'tab.rename': { args: z.object({ tabId, title: z.string().trim().min(1) }), result: empty },
  'tab.reorder': { args: z.object({ tabId, index: z.number().int().nonnegative() }), result: empty },
  // Copies the session (up to an item, if given) into a new tab; refused while the tab runs.
  'tab.fork': { args: z.object({ tabId, newTabId: tabId, upToItemId: z.string().optional() }), result: z.object({ tabId: z.string() }) },
  // Restarts a tab whose process died: the transcript is reloaded from the stored session (new epoch).
  'tab.restart': { args: z.object({ tabId }), result: empty },
  // The snapshot arrives as a `reset` frame on the tab stream, before this reply.
  'tab.subscribe': { args: z.object({ tabId }), result: empty },
  'tab.unsubscribe': { args: z.object({ tabId }), result: empty },
  'tab.history': {
    args: z.object({ tabId, beforeItemId: z.string(), limit: z.number().int().positive().max(1000).optional() }),
    result: z.object({ items: z.array(itemSchema), hasMore: z.boolean() })
  },
  // The cmd id becomes the SDK user-message uuid and the queueId when the message is queued.
  'tab.send': { args: z.object({ tabId, text: z.string().min(1) }), result: z.object({ queued: z.boolean() }) },
  'tab.unqueue': { args: z.object({ tabId, queueId: z.string() }), result: empty },
  'tab.interrupt': { args: z.object({ tabId }), result: empty },
  // model undefined = the default model.
  'tab.setModel': { args: z.object({ tabId, model: z.string().optional() }), result: empty },
  'tab.setMode': { args: z.object({ tabId, mode: permissionModeSchema }), result: empty },
  'tab.models': { args: z.object({ tabId }), result: z.object({ models: z.array(modelInfoSchema) }) },
  'tab.commands': { args: z.object({ tabId }), result: z.object({ commands: z.array(slashCommandSchema) }) },
  // Stored sessions of a folder. rename/delete are refused with session_busy while a tab references the session.
  'sessions.list': { args: z.object({ cwd: z.string().min(1) }), result: z.object({ sessions: z.array(sessionInfoSchema) }) },
  'sessions.rename': { args: z.object({ cwd: z.string().min(1), sessionId: z.string(), title: z.string().trim().min(1) }), result: empty },
  'sessions.delete': { args: z.object({ cwd: z.string().min(1), sessionId: z.string() }), result: empty },
  // Folder trust: what the folder would load and run, and where an accepted trust applies.
  'trust.check': {
    args: z.object({ cwd: z.string().min(1) }),
    result: z.object({ trusted: z.boolean(), config: projectConfigSchema, scope: z.object({ path: z.string(), sessionOnly: z.boolean() }) })
  },
  'trust.grant': { args: z.object({ cwd: z.string().min(1) }), result: empty },
  // Semantic answer: core builds the SDK PermissionResult from the stored request.
  'request.answer': {
    args: z.object({
      tabId,
      requestId: z.string(),
      decision: z.enum(['allow', 'allowAlways', 'deny']),
      reason: z.string().optional(),
      answers: z.record(z.string(), z.string()).optional(),
      planNextMode: permissionModeSchema.optional()
    }),
    result: empty
  }
} as const

export type CommandName = keyof typeof COMMANDS
export type CommandArgs<N extends CommandName> = z.infer<(typeof COMMANDS)[N]['args']>
export type CommandResult<N extends CommandName> = z.infer<(typeof COMMANDS)[N]['result']>
export type ModelInfo = z.infer<typeof modelInfoSchema>
export type SlashCommand = z.infer<typeof slashCommandSchema>
